# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-02 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, default=b'', max_length=254, verbose_name='Email (optional)'),
        ),
    ]
